/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.imolainformatica.ll

import it.imolainformatica.ll.extension.ExpressCodeGeneratorExtension
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class ExpressCodeGeneratorPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register the extension
        project.extensions.create("express", ExpressCodeGeneratorExtension::class.java)

        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'it.imolainformatica.ll.ecg-plugin'")
            }
        }
    }
}
