/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.imolainformatica.ll

import it.imolainformatica.ll.extension.ExpressCodeGeneratorExtension
import it.imolainformatica.ll.task.CodeGeneratorTask
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class ExpressCodeGeneratorPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register the extension
        val extension = project.extensions.create("express", ExpressCodeGeneratorExtension::class.java)

        // Register code generation task
        project.tasks.register("generateCode", CodeGeneratorTask::class.java) {
            it.configuration = extension
            it.doLast { self -> (self as CodeGeneratorTask).generateCode() }
        }
    }
}
